import { Annotation } from "@langchain/langgraph";

/**
 RESEARCHER AGENT STATE

 Input:  A single discovered lead (company + contact basics) + campaign strategy context
 Output: Enriched research intel — pain points, tech stack, businessBrief, score

 The Researcher:
   1. Scrapes the lead's website using Jina Reader (scrapeNode)
   2. Extracts contact details via regex + LLM (contactNode)
   3. Analyzes content with a smart LLM, scoring the lead and extracting intel (analyzeNode)
 */
export const ResearcherStateAnnotation = Annotation.Root({
  // INPUT (set by the worker before invoking the graph)

  leadId: Annotation<string>({
    reducer: (_, b) => b,
  }),

  campaignId: Annotation<string>({
    reducer: (_, b) => b,
  }),

  // Lead identity — what we know so far from the Hunter
  company: Annotation<{
    name: string;
    website: string;
    domain: string;
    industry: string;
    location: string;
    size?: string;
    description?: string;
  }>({
    reducer: (_, b) => b,
  }),

  contact: Annotation<{
    name?: string;
    title?: string;
    email?: string;
    emailSource?: string;
    phone?: string;
    linkedin?: string;
  }>({
    reducer: (_, b) => b,
  }),

  // Agency context — so the researcher can map pain points to OUR services
  agencyContext: Annotation<{
    services: string[];
    uniqueValue: string;
    caseStudies: string[];
  }>({
    reducer: (_, b) => b,
    default: () => ({ services: [], uniqueValue: "", caseStudies: [] }),
  }),

  // Strategy research directives — generated by the Strategist agent
  strategyResearch: Annotation<{
    prioritySignals: string[];
    painPointHypotheses: string[];
    competitorContext: string;
  } | null>({
    reducer: (_, b) => b,
    default: () => null,
  }),

  // INTERMEDIATE (populated by the scrape node) 

  scrapedContent: Annotation<string>({
    reducer: (_, b) => b,
    default: () => "",
  }),

  scrapedPages: Annotation<number>({
    reducer: (_, b) => b,
    default: () => 0,
  }),

  // Contact hints extracted by contactNode via regex (runs on full un-truncated content)
  // Passed to analyzeNode so the merged LLM prompt can pick the best contact
  contactHints: Annotation<{
    emails: string[];
    phones: string[];
    socialLinks: { platform: string; url: string }[];
    hunterVerified: boolean;
  }>({
    reducer: (_, b) => b,
    default: () => ({ emails: [], phones: [], socialLinks: [], hunterVerified: false }),
  }),

  // ── OUTPUT (populated by the analyze node) ──

  research: Annotation<{
    painPoints: string[];
    recentActivity: string[];
    techStack: string[];
    competitors: string[];
    summary: string;            // 2-3 sentence brief for the Outreach agent
    businessBrief: string;      // what they do + exactly how WE can help them
    updatedContact?: {
      name?: string | null;
      title?: string | null;
      email?: string | null;
      phone?: string | null;
      linkedin?: string | null;
      instagram?: string | null;
      emailSource?: "verified" | "corrected" | "guessed";
    };
  }>({
    reducer: (_, b) => b,
    default: () => ({
      painPoints: [],
      recentActivity: [],
      techStack: [],
      competitors: [],
      summary: "",
      businessBrief: "",
    }),
  }),

  score: Annotation<number>({
    reducer: (_, b) => b,
    default: () => 0,
  }),

  disqualified: Annotation<boolean>({
    reducer: (_, b) => b,
    default: () => false,
  }),

  disqualifyReason: Annotation<string | null>({
    reducer: (_, b) => b,
    default: () => null,
  }),

  error: Annotation<string | null>({
    reducer: (_, b) => b,
    default: () => null,
  }),
});

export type ResearcherState = typeof ResearcherStateAnnotation.State;
