"use client"

import React, { useState, useEffect } from 'react';
import { Search, Filter, Mail, CheckCircle2, Clock, Plus, X } from 'lucide-react';
import axios from 'axios';
import { statusStyles, typeStyles } from '@/lib/data/outreach';

export default function OutreachPage() {
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<"all" | "sent" | "drafts">("all");
  const [outreach, setOutreach] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Modal State
  const [selectedDraft, setSelectedDraft] = useState<any | null>(null);
  const [draftSubject, setDraftSubject] = useState("");
  const [draftBody, setDraftBody] = useState("");
  const [sending, setSending] = useState(false);

  useEffect(() => {
    fetchOutreach();
  }, []);

  const fetchOutreach = async () => {
    try {
      const res = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/outreach`, { withCredentials: true });
      if (res.data.success) {
        setOutreach(res.data.data);
      }
    } catch (err) {
      console.error("Failed to fetch outreach", err);
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async () => {
    if (!selectedDraft) return;
    setSending(true);
    try {
      const res = await axios.post(`${process.env.NEXT_PUBLIC_BASE_URL}/api/outreach/${selectedDraft._id}/send`, {
        subject: draftSubject,
        body: draftBody
      }, { withCredentials: true });

      if (res.data.success) {
        setSelectedDraft(null);
        fetchOutreach(); // Refresh the list
      }
    } catch (err) {
      console.error("Failed to send draft", err);
    } finally {
      setSending(false);
    }
  };

  const filtered = outreach.filter(o => {
    const leadName = o.leadId?.contact?.name || "Unknown";
    const companyName = o.leadId?.company?.name || "Unknown";
    const subject = o.message?.subject || "Draft";

    const matchesSearch = 
      leadName.toLowerCase().includes(search.toLowerCase()) ||
      companyName.toLowerCase().includes(search.toLowerCase()) ||
      subject.toLowerCase().includes(search.toLowerCase());

    const isDraft = o.status === "draft";
    
    if (tab === "drafts" && !isDraft) return false;
    if (tab === "sent" && isDraft) return false;

    return matchesSearch;
  });

  return (
    <div className="flex flex-col gap-5 text-foreground">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 bg-card border border-border rounded-xl p-4 md:p-6">
        <div>
          <h2 className="text-lg md:text-xl font-semibold mb-0.5">Outreach Log</h2>
          <p className="text-xs md:text-sm text-muted-foreground">Monitor and approve the actual messages generated by agents.</p>
        </div>
        <button className="flex items-center justify-center gap-2 bg-secondary border border-border hover:bg-foreground/5 text-foreground font-medium px-4 py-2 rounded-lg transition-colors text-sm shrink-0">
          <Filter className="w-4 h-4" /> Views
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-5 items-start">
        {/* Main List */}
        <div className="bg-card border border-border rounded-xl flex flex-col min-h-[500px]">
          {/* Toolbar */}
          <div className="flex flex-col gap-3 p-4 border-b border-border">
            <div className="relative">
              <Search className="w-4 h-4 absolute left-3 top-2.5 text-muted-foreground" />
              <input
                type="text"
                placeholder="Search messages..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full bg-background border border-border rounded-lg pl-9 pr-4 py-2 text-sm text-foreground focus:outline-none focus:border-accent"
              />
            </div>
            <div className="flex bg-secondary border border-border rounded-lg overflow-hidden p-0.5 w-full max-w-sm">
              {(["all", "drafts", "sent"] as const).map(t => (
                <button
                  key={t}
                  onClick={() => setTab(t)}
                  className={`flex-1 px-2 py-1.5 text-xs font-semibold capitalize rounded-md transition-colors ${tab === t ? 'bg-background shadow-sm text-foreground' : 'text-muted-foreground hover:text-foreground'}`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {/* List */}
          <div className="divide-y divide-border/50">
            {loading ? (
              <div className="p-8 text-center text-sm text-muted-foreground animate-pulse">Loading messages...</div>
            ) : filtered.map((msg) => {
              const s = statusStyles[msg.status as keyof typeof statusStyles] || statusStyles.draft;
              const leadName = msg.leadId?.contact?.name || "Unknown";
              const companyName = msg.leadId?.company?.name || "Unknown";
              const subject = msg.message?.subject || "Draft pending";
              const body = msg.message?.body || "";
              const date = new Date(msg.createdAt).toLocaleDateString();

              return (
                <div 
                  key={msg._id} 
                  onClick={() => {
                    if (msg.status === "draft") {
                      setSelectedDraft(msg);
                      setDraftSubject(msg.message?.subject || "");
                      setDraftBody(msg.message?.body || "");
                    }
                  }}
                  className={`p-4 flex gap-3 transition-colors ${msg.status === "draft" ? "cursor-pointer hover:bg-foreground/5" : "hover:bg-foreground/2"}`}
                >
                  <div className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 mt-0.5 ${s.bg}`}>
                    {msg.status === 'sent' || msg.status === 'delivered' ? <CheckCircle2 className={`w-4 h-4 ${s.text}`} /> :
                     <Mail className={`w-4 h-4 ${s.text}`} />}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-1 mb-1">
                      <div className="flex items-center gap-1.5 min-w-0">
                        <span className="font-semibold text-foreground text-sm truncate">{leadName}</span>
                        <span className="text-muted-foreground text-xs shrink-0">@ {companyName}</span>
                      </div>
                      <div className="flex items-center gap-2 shrink-0">
                        <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded border border-border/50 ${s.text}`}>
                          {msg.status === "draft" ? "NEEDS REVIEW" : msg.status}
                        </span>
                        <span className="text-xs text-muted-foreground">{date}</span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-medium text-foreground truncate">{subject}</span>
                    </div>
                    <p className="text-xs text-muted-foreground line-clamp-2">{body}</p>
                  </div>
                </div>
              );
            })}
            {!loading && filtered.length === 0 && (
              <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                <Mail className="w-8 h-8 mb-3 opacity-20" />
                <p className="text-sm">No messages found.</p>
              </div>
            )}
          </div>
        </div>

        {/* Templates sidebar */}
        <div className="flex flex-col gap-5">
          <div className="bg-card border border-border rounded-xl p-5">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-sm font-semibold">Sending Stats</h3>
            </div>
            <div className="flex justify-between items-center py-2 border-b border-border/50">
              <span className="text-sm text-muted-foreground">Drafts Pending</span>
              <span className="text-sm font-medium">{outreach.filter(o => o.status === "draft").length}</span>
            </div>
            <div className="flex justify-between items-center py-2 border-b border-border/50">
              <span className="text-sm text-muted-foreground">Sent Total</span>
              <span className="text-sm font-medium">{outreach.filter(o => o.status === "sent").length}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Draft Review Modal */}
      {selectedDraft && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-card border border-border rounded-2xl w-full max-w-2xl overflow-hidden flex flex-col shadow-2xl">
            <div className="flex justify-between items-center p-4 border-b border-border">
              <div>
                <h3 className="font-semibold text-lg">Review Draft</h3>
                <p className="text-xs text-muted-foreground">To: {selectedDraft.leadId?.contact?.name} ({selectedDraft.leadId?.contact?.email})</p>
              </div>
              <button onClick={() => setSelectedDraft(null)} className="p-2 hover:bg-secondary rounded-lg transition-colors">
                <X className="w-5 h-5 text-muted-foreground" />
              </button>
            </div>
            
            <div className="p-5 flex flex-col gap-4">
              <div>
                <label className="text-xs font-semibold text-muted-foreground mb-1 block">Subject</label>
                <input 
                  type="text" 
                  value={draftSubject}
                  onChange={e => setDraftSubject(e.target.value)}
                  className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-accent"
                />
              </div>
              <div>
                <label className="text-xs font-semibold text-muted-foreground mb-1 block">Body</label>
                <textarea 
                  value={draftBody}
                  onChange={e => setDraftBody(e.target.value)}
                  rows={12}
                  className="w-full bg-background border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-accent resize-none"
                />
              </div>
            </div>

            <div className="p-4 border-t border-border bg-secondary flex justify-end gap-3">
              <button 
                onClick={() => setSelectedDraft(null)}
                className="px-4 py-2 text-sm font-medium hover:bg-background border border-transparent hover:border-border rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleApprove}
                disabled={sending || !draftSubject || !draftBody}
                className="px-6 py-2 bg-accent hover:bg-accent/90 text-black text-sm font-medium rounded-lg transition-colors disabled:opacity-50 flex items-center gap-2"
              >
                {sending ? "Sending..." : "Approve & Send"}
                {!sending && <Mail className="w-4 h-4" />}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
