import mongoose, { Schema, Document } from "mongoose";

export type CampaignStatus = "draft" | "active" | "paused" | "completed" | "archived";
export type OutreachChannel = "email" | "whatsapp" | "linkedin" | "instagram"; // extensible

export interface ICampaign extends Document {
  name: string;
  status: CampaignStatus;
  instructions?: string;
  autoSend: boolean;

  // Strategy — generated by the Strategist agent
  strategy?: {
    icp: {
      idealCompanyProfile: string;
      searchAngles: string[];
      qualificationCriteria: string[];
      disqualifiers: string[];
    };
    outreach: {
      tone: string;
      openingStrategy: string;
      valueProposition: string;
      callToAction: string;
      followUpStrategy: string;
      avoidTopics: string[];
    };
    research: {
      prioritySignals: string[];
      painPointHypotheses: string[];
      competitorContext: string;
    };
    reply: {
      objectionHandling: Record<string, string>;
      qualificationQuestions: string[];
      bookingTriggers: string[];
    };
    targetCities: string[];
    currentCityIndex: number;
    usedQueries: string[];
    summary: string;
    generatedAt: Date;
  };
  // Hunt config — what Hunter agent uses
  target: {
    industry: string;            // e.g. "real estate", "e-commerce", "law firms"
    location: {
      country: string;
      state?: string;
      city?: string;
    };            // e.g. "Dubai, UAE" or "United States"
    keywords: string[];          // e.g. ["property management", "luxury listings"]
    companySize?: string;        // e.g. "1-10", "10-50"
    excludeDomains: string[];    // already contacted or blacklisted
  };

  // Outreach config
  channel: OutreachChannel;


  // Stats — updated by agents
  stats: {
    leadsFound: number;
    leadsResearched: number;
    emailsSent: number;
    emailsOpened: number;
    replies: number;
    callsBooked: number;
    proposalsSent: number;
  };

  // Schedule
  schedule: {
    startDate?: Date;
    endDate?: Date;
    dailyLimit: number;          // daily limit for this campaign
    schedule: number;            // scheduled hour (0-23)
    followUpDays: number[];      // e.g. [3, 7]
    warmupMode: boolean;         // if true, caps at 10/day initially
  };

  nextRunAt?: Date;
  lastRunAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const CampaignSchema = new Schema<ICampaign>(
  {
    name: { type: String, required: true, trim: true },
    instructions: { type: String },
    autoSend: { type: Boolean, default: false },

    strategy: {
      icp: {
        idealCompanyProfile: { type: String },
        searchAngles: [{ type: String }],
        qualificationCriteria: [{ type: String }],
        disqualifiers: [{ type: String }],
      },
      outreach: {
        tone: { type: String },
        openingStrategy: { type: String },
        valueProposition: { type: String },
        callToAction: { type: String },
        followUpStrategy: { type: String },
        avoidTopics: [{ type: String }],
      },
      research: {
        prioritySignals: [{ type: String }],
        painPointHypotheses: [{ type: String }],
        competitorContext: { type: String },
      },
      reply: {
        objectionHandling: { type: Schema.Types.Mixed, default: {} },
        qualificationQuestions: [{ type: String }],
        bookingTriggers: [{ type: String }],
      },
      targetCities: [{ type: String }],
      currentCityIndex: { type: Number, default: 0 },
      usedQueries: [{ type: String }],
      summary: { type: String },
      generatedAt: { type: Date },
    },
    status: {
      type: String,
      enum: ["draft", "active", "paused", "completed", "archived"],
      default: "draft",
    },

    target: {
      industry: { type: String, required: true },
      location: { country: { type: String, required: true }, state: { type: String }, city: { type: String } },
      keywords: [{ type: String }],
      companySize: { type: String },
      excludeDomains: [{ type: String }],
    },

    channel: {
      type: String,
      enum: ["email", "whatsapp", "linkedin", "instagram"],
      default: "email",
    },


    stats: {
      leadsFound: { type: Number, default: 0 },
      leadsResearched: { type: Number, default: 0 },
      emailsSent: { type: Number, default: 0 },
      emailsOpened: { type: Number, default: 0 },
      replies: { type: Number, default: 0 },
      callsBooked: { type: Number, default: 0 },
      proposalsSent: { type: Number, default: 0 },
    },

    schedule: {
      startDate: { type: Date },
      endDate: { type: Date },
      dailyLimit: { type: Number, default: 30 },
      schedule: {
        type: Number,
        required: true,
      },
      followUpDays: { type: [Number], default: [3, 7] },
      warmupMode: { type: Boolean, default: true },
    },

    nextRunAt: { type: Date },
    lastRunAt: { type: Date },
  },
  { timestamps: true }
);

CampaignSchema.index({ status: 1 });

export const Campaign = mongoose.model<ICampaign>("Campaign", CampaignSchema);