"use client"

import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Target, Search, PenTool, MessageSquare, CheckCircle2, AlertCircle, MapPin, SearchSlash, List } from 'lucide-react'

interface StrategyViewerProps {
  isOpen: boolean
  onClose: () => void
  strategy: any
}

export function StrategyViewer({ isOpen, onClose, strategy }: StrategyViewerProps) {
  const [activeTab, setActiveTab] = useState<'icp' | 'research' | 'outreach' | 'reply'>('icp')

  if (!strategy) return null

  const tabs = [
    { id: 'icp', label: 'ICP & Targeting', icon: Target },
    { id: 'research', label: 'Research & Angles', icon: Search },
    { id: 'outreach', label: 'Outreach Copy', icon: PenTool },
    { id: 'reply', label: 'Reply Handling', icon: MessageSquare },
  ] as const

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center overflow-hidden">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-background/80 backdrop-blur-sm"
          />

          {/* Modal Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: "spring", damping: 25, stiffness: 300 }}
            className="relative w-full max-w-6xl max-h-[90vh] bg-card border border-border shadow-2xl rounded-2xl flex flex-col overflow-hidden m-4"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-border/50 bg-background/50">
              <div>
                <h2 className="text-2xl font-bold text-foreground">Campaign Strategy</h2>
                <p className="text-sm text-muted-foreground mt-1 flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-accent animate-pulse" />
                  Generated by AI Strategist
                </p>
              </div>
              <button
                onClick={onClose}
                className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-foreground/5 text-muted-foreground transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex flex-col md:flex-row flex-1 overflow-hidden">
              {/* Sidebar Tabs */}
              <div className="w-full md:w-64 border-r border-border/50 bg-background/30 p-4 flex flex-row md:flex-col gap-2 overflow-x-auto md:overflow-y-auto">
                {tabs.map((tab) => {
                  const Icon = tab.icon
                  const isActive = activeTab === tab.id
                  return (
                    <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id)}
                      className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all whitespace-nowrap md:whitespace-normal text-left
                        ${isActive 
                          ? 'bg-accent/10 text-accent font-medium shadow-sm' 
                          : 'text-muted-foreground hover:bg-foreground/5 hover:text-foreground'
                        }`}
                    >
                      <Icon className={`w-5 h-5 ${isActive ? 'text-accent' : 'text-muted-foreground'}`} />
                      {tab.label}
                    </button>
                  )
                })}
              </div>

              {/* Content Area */}
              <div className="flex-1 overflow-y-auto p-6 md:p-8 bg-background/20 relative">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={activeTab}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                    className="max-w-4xl mx-auto space-y-8"
                  >
                    {activeTab === 'icp' && strategy.icp && (
                      <div className="space-y-6">
                        <Section title="Ideal Company Profile" icon={Target}>
                          <p className="text-foreground leading-relaxed">{strategy.icp.idealCompanyProfile}</p>
                        </Section>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <ListCard title="Search Angles" items={strategy.icp.searchAngles} icon={Search} iconColor="text-blue-400" />
                          <ListCard title="Target Cities" items={strategy.targetCities} icon={MapPin} iconColor="text-purple-400" />
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <ListCard title="Qualification Criteria" items={strategy.icp.qualificationCriteria} icon={CheckCircle2} iconColor="text-emerald-400" />
                          <ListCard title="Disqualifiers" items={strategy.icp.disqualifiers} icon={SearchSlash} iconColor="text-red-400" />
                        </div>
                      </div>
                    )}

                    {activeTab === 'research' && strategy.research && (
                      <div className="space-y-6">
                        <Section title="Competitor Context" icon={List}>
                          <p className="text-foreground leading-relaxed">{strategy.research.competitorContext}</p>
                        </Section>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <ListCard title="Priority Signals" items={strategy.research.prioritySignals} icon={Target} iconColor="text-emerald-400" />
                          <ListCard title="Pain Point Hypotheses" items={strategy.research.painPointHypotheses} icon={AlertCircle} iconColor="text-amber-400" />
                        </div>
                      </div>
                    )}

                    {activeTab === 'outreach' && strategy.outreach && (
                      <div className="space-y-6">
                        <Section title="Opening Strategy" icon={PenTool}>
                          <p className="text-foreground leading-relaxed">{strategy.outreach.openingStrategy}</p>
                        </Section>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                          <Section title="Value Proposition" className="h-full">
                            <p className="text-foreground leading-relaxed">{strategy.outreach.valueProposition}</p>
                          </Section>
                          <Section title="Call To Action" className="h-full">
                            <p className="text-foreground leading-relaxed">{strategy.outreach.callToAction}</p>
                          </Section>
                        </div>

                        <Section title="Follow-up Strategy">
                          <p className="text-foreground leading-relaxed">{strategy.outreach.followUpStrategy}</p>
                        </Section>

                        <div className="flex gap-2 items-center flex-wrap">
                          <span className="text-sm font-semibold text-muted-foreground mr-2">Avoid Topics:</span>
                          {strategy.outreach.avoidTopics?.map((topic: string, i: number) => (
                            <span key={i} className="px-3 py-1 bg-red-500/10 text-red-400 text-xs rounded-full border border-red-500/20">
                              {topic}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {activeTab === 'reply' && strategy.reply && (
                      <div className="space-y-6">
                        <Section title="Handling Guidelines" icon={MessageSquare}>
                          <p className="text-foreground leading-relaxed whitespace-pre-wrap">{strategy.reply.guidelines}</p>
                        </Section>
                        
                        <Section title="Agent Instructions" icon={CheckCircle2}>
                          <p className="text-foreground leading-relaxed whitespace-pre-wrap">{strategy.reply.instructions}</p>
                        </Section>

                        <ListCard title="Booking Triggers" items={strategy.reply.bookingTriggers} icon={CheckCircle2} iconColor="text-emerald-400" />

                        {strategy.reply.objectionApproaches && Object.keys(strategy.reply.objectionApproaches).length > 0 && (
                          <Section title="Objection Handling Matrix">
                            <div className="grid grid-cols-1 gap-4">
                              {Object.entries(strategy.reply.objectionApproaches).map(([objection, approach]: [string, any], i: number) => (
                                <div key={i} className="p-4 rounded-xl bg-background/50 border border-border/50">
                                  <h4 className="font-semibold text-foreground mb-2 flex items-center gap-2">
                                    <AlertCircle className="w-4 h-4 text-amber-400" />
                                    {objection}
                                  </h4>
                                  <p className="text-sm text-muted-foreground leading-relaxed pl-6">{approach}</p>
                                </div>
                              ))}
                            </div>
                          </Section>
                        )}
                      </div>
                    )}

                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}

// Helper Components

function Section({ title, icon: Icon, children, className = '' }: any) {
  return (
    <div className={`p-6 rounded-2xl bg-card border border-border/50 shadow-sm ${className}`}>
      <h3 className="text-base font-bold text-foreground mb-4 flex items-center gap-2">
        {Icon && <Icon className="w-5 h-5 text-accent" />}
        {title}
      </h3>
      {children}
    </div>
  )
}

function ListCard({ title, items, icon: Icon, iconColor = 'text-accent' }: any) {
  if (!items || items.length === 0) return null
  return (
    <div className="p-6 rounded-2xl bg-card border border-border/50 shadow-sm h-full">
      <h3 className="text-base font-bold text-foreground mb-4 flex items-center gap-2">
        {Icon && <Icon className={`w-5 h-5 ${iconColor}`} />}
        {title}
      </h3>
      <ul className="space-y-3">
        {items.map((item: string, i: number) => (
          <li key={i} className="flex items-start gap-3 text-sm text-muted-foreground leading-relaxed">
            <span className={`mt-1.5 w-1.5 h-1.5 rounded-full shrink-0 bg-current ${iconColor}`} />
            {item}
          </li>
        ))}
      </ul>
    </div>
  )
}
