import { getLLM } from "../../../../lib/ai";
import { Campaign } from "../../../../models/campaign.model";
import type { HunterState } from "../state";
import { buildQueriesPrompt } from "../prompts";

export async function queryBuilderNode(state: HunterState): Promise<Partial<HunterState>> {
  try {
    // 1. Load the latest hunterState from DB to get the resume cursor
    const campaign = await Campaign.findById(state.campaignId);
    if (!campaign) throw new Error("Campaign not found");

    const hs = campaign.hunterState ?? {
      currentRegionIndex: 0,
      currentQuery: undefined,
      currentOffset: 0,
      exhaustedRegions: [],
    };

    // 2. Determine the active region.
    // If the strategy has targetCities, cycle through them. Otherwise fall back to target.location.
    const targetCities: string[] = campaign.strategy?.targetCities ?? [];
    const exhaustedRegions: string[] = hs.exhaustedRegions ?? [];

    // Find the next non-exhausted region
    let activeRegionIndex = hs.currentRegionIndex ?? 0;
    let activeCity: string | null = null;

    if (targetCities.length > 0) {
      // Walk from currentRegionIndex to find a non-exhausted city
      for (let i = 0; i < targetCities.length; i++) {
        const idx = (activeRegionIndex + i) % targetCities.length;
        const city = targetCities[idx]!;
        if (!exhaustedRegions.includes(city)) {
          activeCity = city;
          activeRegionIndex = idx;
          break;
        }
      }
      // All cities exhausted — reset and start over
      if (!activeCity) {
        console.log("[QueryBuilder] All regions exhausted — resetting exhaustedRegions and starting over.");
        activeCity = targetCities[0]!;
        activeRegionIndex = 0;
        await Campaign.findByIdAndUpdate(state.campaignId, {
          $set: { "hunterState.exhaustedRegions": [] },
        });
      }
    }

    // 3. Build the effective location for query generation
    const effectiveLocation = activeCity
      ? { ...campaign.target.location, city: activeCity }
      : campaign.target.location;

    console.log(`[QueryBuilder] Active region: "${activeCity ?? [effectiveLocation.city, effectiveLocation.country].filter(Boolean).join(", ")}"`);

    // 4. Generate queries via LLM
    const llm = getLLM("fast");
    const prompt = buildQueriesPrompt(
      {
        industry: campaign.target.industry,
        location: effectiveLocation,
        keywords: campaign.target.keywords,
        companySize: campaign.target.companySize,
      },
      state.strategy,
    );

    const response = await llm.invoke([
      { role: "system", content: prompt },
      { role: "user", content: "Generate the search queries now." },
    ]);

    const raw = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
    const cleaned = raw.replace(/```json/g, "").replace(/```/g, "").trim();

    let queries: string[] = [];
    try {
      queries = JSON.parse(cleaned);
    } catch {
      // Fallback: parse line by line
      queries = cleaned.split("\n").map(q => q.replace(/^\d+\.\s*/, "").replace(/^-\s*/, "").trim()).filter(q => q.length > 5);
    }

    if (!Array.isArray(queries) || queries.length === 0) {
      throw new Error("No queries generated by LLM");
    }

    // 5. Filter out any queries already used globally across all runs
    const usedGlobal: string[] = campaign.strategy?.usedQueries ?? [];
    const freshQueries = queries.filter(q => !usedGlobal.includes(q) && q !== hs.currentQuery);
    
    // 6. Prepend the unfinished query from yesterday (if any)
    const finalQueries = freshQueries.length > 0 ? freshQueries : queries;
    if (hs.currentQuery) {
      finalQueries.unshift(hs.currentQuery);
      console.log(`[QueryBuilder] Prepended unfinished query from previous run: "${hs.currentQuery}"`);
    }

    console.log(`[QueryBuilder] Generated ${finalQueries.length} queries for region "${activeCity}"`);

    return {
      queries: finalQueries,
      currentRegionIndex: activeRegionIndex,
      currentQuery: hs.currentQuery, // keep it tracked in state
      currentOffset: hs.currentOffset ?? 0,
      exhaustedRegions,
    };
  } catch (error) {
    console.error("[QueryBuilder] Error:", error);
    return { errors: ["Query generation failed"], done: true };
  }
}